---
- name: Deploy apps
  hosts: homelab
  become: true
  roles:
    - { role: apps/traefik, tags: [never, traefik] }
    - { role: apps/minio, tags: [never, minio] }
    - { role: apps/authentik, tags: [never, authentik] }
    - { role: apps/gitea, tags: [never, gitea] }
    - { role: apps/nextcloud, tags: [never, nextcloud] }
    - { role: apps/registry, tags: [never, registry] }
    - { role: apps/pihole, tags: [never, pihole] }
    - { role: apps/ollama, tags: [never, llm] }
    - { role: apps/anythingllm, tags: [never, llm] }
    - { role: apps/passkey, tags: [never, passkey, template] }
    - { role: apps/copy-me, tags: [never, template] }