---
- name: Deploy apps
  hosts: homelab
  become: true
  roles:
    - { role: apps/traefik, tags: [never, all, traefik] }
    - { role: apps/minio, tags: [never, all, minio] }
    - { role: apps/authentik, tags: [never, all, authentik] }
    - { role: apps/gitea, tags: [never, all, gitea] }
    - { role: apps/nextcloud, tags: [never, all, nextcloud] }
    - { role: apps/pihole, tags: [never, pihole] }
    - { role: apps/ollama, tags: [never, llm] }
    - { role: apps/anythingllm, tags: [never, llm] }
    - { role: apps/copy-me, tags: [never, template] }