---
- name: Deploy apps
  hosts: homelab
  become: true
  roles:
    - { role: apps/traefik, tags: [never, traefik] } 
    - { role: apps/minio, tags: [never, minio] } 
    - { role: apps/authentik, tags: [never, authentik] } 