---
- name: Deploy apps
  hosts: homelab
  become: true
  roles:
    - { role: apps/traefik, tags: [never, all, traefik] } 
    - { role: apps/minio, tags: [never, all, minio] } 
    - { role: apps/authentik, tags: [never, all, authentik] } 
    - { role: apps/gitea, tags: [never, all, gitea] } 