---
app_name: "pihole"
app_folder: "{{ apps_location}}/{{ app_name }}"
config_folder: "{{ app_folder }}/config"
storage_folder: "{{ zfs_pool }}/pihole"
app_storage: "{{ storage_folder }}/app"
dnsmasq_storage: "{{ storage_folder }}/dnsmasq"

directories: 
  - "{{ app_folder }}"
  - "{{ app_storage }}"
  - "{{ dnsmasq_storage }}"

templates:
  - { template: "docker-compose.yml.j2", dest: "{{ app_folder }}/docker-compose.yml" }
  - { template: "pihole_passwd.j2", dest: "{{ app_folder }}/.pihole_passwd" }