---
app_name: "minio"
app_folder: "{{ apps_location }}/{{ app_name }}"

directories: 
  - "{{ app_folder }}"

templates:
  - { template: "docker-compose.yml.j2", dest: "{{ app_folder }}/docker-compose.yml" }