---
app_name: "registry"
app_port: 5000
app_folder: "{{ apps_location }}/{{ app_name }}"
storage_folder: "{{ zfs_pool }}/{{ app_name }}"
app_storage: "{{ storage_folder }}/data"

directories: 
  - "{{ app_folder }}"
  - "{{ app_storage }}"

templates:
  - { template: "docker-compose.yml.j2", dest: "{{ app_folder }}/docker-compose.yml" }