---
app_folder: "/{{ role_name }}"
config_folder: "{{ app_folder }}/config"

directories: 
  - "{{ app_folder }}"
  - "{{ config_folder }}"

templates:
  - { template: "docker-compose.yml.j2", dest: "{{ app_folder }}/docker-compose.yml" }
  - { template: "traefik.yml.j2", dest: "{{ config_folder }}/traefik.yml" }