traefik_admin_pass: "$$apr1$$fjr6T0hX$$QXal.rOVtN/ngsjpvrMOe."
# 234kno2i3h456b213ibr23rbn

authentik_pg_pass: 93hf2903hf2h3f90
authentik_secret_key: Gr4ZuDhgSoKmq8bJmOXm/k659AkhmVefe1dBLHksLJPAWaM0MG1HOkY/1omWG6UcKWYGPSGWUtNSsaWu